name: Update GitHub Pages

# 触发条件：每天定时执行
on:
  schedule:
    - cron: '0 */30 * * * *'  # 每半个小时 执行，可以根据需要修改时间
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 安装 Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # 安装需要的 Python 包

    - name: Run script to generate HTML
      run: |
        python daily-activity-report.py  # 运行你的 Python 脚本来生成 report.html

    - name: Check if report.html is generated
      run: |
        if [ -f "./report.html" ]; then
          echo "报告文件已生成：report.html"
        else
          echo "报告文件未生成：report.html"
          exit 1  # 如果文件未生成，终止工作流
        fi

    - name: Commit and push the changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add report.html
        git commit -m "Update report.html with new activity data" || echo "No changes to commit"
        git push origin main
